name: scannetter
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - appdirs=1.4.4=pyh9f0ad1d_0
  - brotlipy=0.7.0=py38h0a891b7_1005
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.12.7=ha878542_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py38h4a40e3a_3
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cryptography=39.0.1=py38h3d167d9_0
  - freetype=2.12.1=hca18f0e_1
  - idna=3.4=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - lcms2=2.14=hfd0df8a_1
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=16_linux64_openblas
  - libcblas=3.9.0=16_linux64_openblas
  - libdeflate=1.17=h0b41bf4_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=12.2.0=h65d4601_19
  - liblapack=3.9.0=16_linux64_openblas
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libpng=1.6.39=h753d276_0
  - libsqlite=3.40.0=h753d276_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libzlib=1.2.13=h166bdaf_4
  - ncurses=6.3=h27087fc_1
  - numpy=1.24.2=py38h10c12cc_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.0.8=h0b41bf4_0
  - packaging=23.0=pyhd8ed1ab_0
  - pillow=9.4.0=py38hde6dc18_1
  - pip=23.0=pyhd8ed1ab_0
  - pooch=1.6.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyquaternion=0.9.9=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.16=he550d4f_1_cpython
  - python_abi=3.8=3_cp38
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.2=pyhd8ed1ab_0
  - setuptools=67.1.0=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tqdm=4.64.1=pyhd8ed1ab_0
  - urllib3=1.26.14=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - zstd=1.5.2=h3eb15da_6
  - pip:
    - addict==2.4.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - async-timeout==4.0.2
    - attrs==22.2.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.2
    - bleach==6.0.0
    - click==8.1.3
    - coloredlogs==15.0.1
    - comm==0.1.2
    - configargparse==1.5.3
    - contourpy==1.0.7
    - cycler==0.11.0
    - dash==2.8.1
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - debugpy==1.6.6
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docker-pycreds==0.4.0
    - executing==1.2.0
    - fastjsonschema==2.16.3
    - filelock==3.9.0
    - flask==2.2.3
    - fonttools==4.39.0
    - fqdn==1.5.1
    - frozenlist==1.3.3
    - fsspec==2023.3.0
    - gdown==4.6.4
    - gitdb==4.0.10
    - gitpython==3.1.31
    - h5py==3.8.0
    - humanfriendly==10.0
    - imageio==2.26.0
    - importlib-metadata==6.0.0
    - importlib-resources==5.12.0
    - ipykernel==6.21.3
    - ipython==8.11.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.4
    - isoduration==20.11.0
    - itsdangerous==2.1.2
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter==1.0.0
    - jupyter-client==8.0.3
    - jupyter-console==6.6.3
    - jupyter-core==5.2.0
    - jupyter-events==0.6.3
    - jupyter-server==2.4.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.5
    - kiwisolver==1.4.4
    - kornia==0.6.10
    - lazy-loader==0.1
    - lightning-utilities==0.8.0
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - mistune==2.0.5
    - multidict==6.0.4
    - nbclassic==0.5.3
    - nbclient==0.7.2
    - nbconvert==7.2.9
    - nbformat==5.5.0
    - nest-asyncio==1.5.6
    - networkx==3.0
    - ninja==1.10.2.3
    - notebook==6.5.3
    - notebook-shim==0.2.2
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - open3d==0.16.0
    - opencv-python==4.7.0.72
    - pandas==1.5.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pkgutil-resolve-name==1.3.10
    - platformdirs==3.1.0
    - plotly==5.13.1
    - prometheus-client==0.16.0
    - prompt-toolkit==3.0.38
    - protobuf==4.22.1
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycolmap==0.3.0
    - pygments==2.14.0
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - pytorch-lightning==1.9.4
    - pytz==2022.7.1
    - pywavelets==1.4.1
    - pyyaml==6.0
    - pyzmq==25.0.0
    - qtconsole==5.4.0
    - qtpy==2.3.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - scikit-image==0.20.0
    - scikit-learn==1.2.2
    - scipy==1.9.1
    - send2trash==1.8.0
    - sentry-sdk==1.16.0
    - setproctitle==1.3.2
    - six==1.16.0
    - smmap==5.0.0
    - sniffio==1.3.0
    - soupsieve==2.4
    - stack-data==0.6.2
    - tenacity==8.2.2
    - terminado==0.17.1
    - threadpoolctl==3.1.0
    - tifffile==2023.2.28
    - tinycss2==1.2.1
    - torch==1.13.1
    - torchmetrics==0.11.3
    - torchvision==0.14.1
    - tornado==6.2
    - traitlets==5.9.0
    - trimesh==3.11.2
    - typing-extensions==4.5.0
    - uri-template==1.2.0
    - wandb==0.13.11
    - wcwidth==0.2.6
    - webcolors==1.12
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - werkzeug==2.2.3
    - widgetsnbextension==4.0.5
    - yarl==1.8.2
    - zipp==3.15.0
prefix: /home/weders/anaconda3/envs/scannetter
